spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
server:
  port: 8090


logging:
  level:
    com:
      exception: info
  file:
    name: G:/pdfinfo/forqc/spring.log
